builds:
  - goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - 386

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "386" }}i386{{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
